name: 'Release Packages'
description: 'Release All packages To Set Registry'

inputs:
  registry-token:
    required: true
    description: 'Auth-Token to push packages to registry'
  registry-url:
    required: true
    description: 'Registry URL'
  registry-scope:
    required: true
    description: 'Package scope'

runs:
  using: 'composite'
  steps:
    env:
      NODE_AUTH_TOKEN: ${{ inputs.registry-token }}

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.registry-scope }}
        
    # Clean NPM Install
    - name: NPM install
      run: npm ci --ignore-scripts
    # Build
    - name: Build
      run: npm run build -- --force
    # Release Public Packages
    - name: Release
      run: npm publish -ws --access public