name: Bump package versions

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version to bump to'
        required: false

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite test.
      - name: 'Test Packages'
        uses: ./.github/actions/npm-test

  bump-version:
    if: ${{ !contains(github.event.head_commit.message, '[Version-Bump]') }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite bump version.
      - name: 'Bump Version'
        uses: ./.github/actions/bump-version
        with:
          version-type: ${{ inputs.version-type }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  empty-job:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Catch no job
        run: echo "Catch no job"

 
      
