name: NPM Package Release

on:
  release:
    types: [published]

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite test.
      - name: 'Test Packages'
        uses: ./.github/actions/npm-test

  publish-npm-packages:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite package release.
      - name: 'Test Packages'
        uses: ./.github/actions/release-packages
        with:
          registry-token: ${{ secrets.CI_NPM_TOKEN }}
          registry-url: 'https://registry.npmjs.org'
          registry-scope: '@kartoffelgames'