name: 'Release version'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite test.
      - name: 'Test Packages'
        uses: ./.github/actions/npm-test

  publish-npm-packages:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Create bad changelog
      - name: Generate Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: generate-changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.generate-changelog.outputs.changelog }}
          draft: false
          prerelease: false