name: Test All Packages

on:
  push:
  pull_request:
    branches:
      - 'development'
      - 'master'

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: NPM Install
        run: npm ci --ignore-scripts

      - name: Tests
        run: npm run test



      
