name: Test All Packages

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite test.
      - name: 'Test Packages'
        uses: ./.github/actions/npm-test



      
